### ISSUE TITLE
Notification Interval and Profiles not working for me

### ISSUE THREAD

**Issue by skein12** [shayaantx/botdarr#101]
![Screen Shot 2023-05-07 at 7 39 51 PM](https://user-images.githubusercontent.com/114792431/236721965-f01ded12-6742-46d0-a19d-5499454d6635.png)
Maybe I'm doing something wrong but every 5 minutes I'm told the downloads but I have it set to every 180 minutes. Also how do I use a none default profile? The Readme says (i.e., show add ANY) but I've tried adding it after in discord and it just searches for that. There seems to be no field for profile.

**Comment by shayaantx** [comment]
@skein12 

If its getting set to 5 minutes, that means the NOTIFICATION_INTERVAL for some reason is not being set, can you zip up the logs and post them? If you want I can add you on discord and we can troubleshoot live sometime (as it looks like you're using some tool to manage your containers and something weird might be happening with it) - I will confirm tonight NOTIFICATION_INTERVAL actually works on my box

Regarding your profile question, there is nothing to specify an profile from a command. The way you specify profiles is via environment variables (like NOTIFICATION_INTERVAL or MAX_DOWNLOADS_TO_SHOW), for radarr for example, radarr-default-profile (you would set this to the name of your profile).

If you want to see profiles for radarr, sonarr, lidarr there are commands like in the help list see the profiles available.

If you want the ability to include a profile parameter in the add commands, please put in a separate issue for that.

**Comment by shayaantx** [comment]
please reopen if you continue to have issues or if you want we can chat live on discord, telegram, or wherever to troubleshoot more
