### ISSUE TITLE
!Music Artist Add ####

### ISSUE THREAD

**Issue by sowie2016** [shayaantx/botdarr#103]
When runnig

!music artist add via the telegram bot I always get the response 

Info! - Too many artists found, please narrow search or increase max results to show

I have tried more obscure artists and also added the variable -e MAX_RESULTS_TO_SHOW="500"

The "!music artist find existing" & "!music downloads" work fine so my connection to lidarr is working. Any pointers?

**Comment by shayaantx** [comment]
@sowie2016 which artist are you trying to add? 

Usually when it shows "Too many artists found, please narrow search or increase max results to show" it should be showing the results afterward. Are you saying its showing nothing at all?

**Comment by sowie2016** [comment]
Yes that's all it returns.

I tried a few different artists all returning the same error..

!music artist add michael jackson

I added sonarr & radarr just to test and these all returned shows/movies as expected.

**Comment by shayaantx** [comment]
@sowie2016 I'll look tomorrow morning and get back to you, sounds like a bug

**Comment by sowie2016** [comment]
Thank You

**Comment by shayaantx** [comment]
The underlying telegram api was throwing the following error message

```
Bad Request: BUTTON_DATA_INVALID
```

Something has changed in the telegram bot api that is causing the buttons that get appended to each downloadable item to be broken now...

Either its the fact the callbacks are larger than 64 bytes and now they are actually enforcing it (https://core.telegram.org/bots/api#inlinekeyboardbutton) - even tho I don't recall this happening with telegram before. Or there is some content causing the telegram api to reject the callback data.

Still investigating

**Comment by shayaantx** [comment]
Looks like they are def no longer allowing callbacks for buttons that are larger than 64 bytes, I'll need to come up with some fix for this (I'll look a bit later tonight or tomorrow night and get back to you)

**Comment by shayaantx** [comment]
So I put up a PR to fix this, https://github.com/shayaantx/botdarr/pull/105, it seems to work, I'll merge it tomorrow (wanna add some tests maybe if I'm not lazy)

@sowie2016

**Comment by sowie2016** [comment]
Perfet will wait for the merge and updated docker image

**Comment by shayaantx** [comment]
merged this, should be available in latest version 5.6.7

gonna close this, lemme know if you have any issues

keep in mind the telegram buttons are basically last for 10 days or so (so if someone was to click "add" after 10 days it wouldn't work anymore, they would have to search for content again this applies to shows, movies too)
