### ISSUE TITLE
Telegram Group bug

### ISSUE THREAD

**Issue by Sephiphi** [shayaantx/botdarr#113]
Hello,

Thank's again for your application, and I'm happy to see thet you added buttons on Telegram discussions recently.

Related to Telegram, it seems that I have an issue there.
I'm using a group to configure my LIDARR library and the bot doesn't seem to be allowed to discuss on the group.

I have the following line on the logs : 
2023-Oct-02 21:52:20 PM [pool-5-thread-2] WARN  TelegramLog - Channel BlahBlah not allowed, check properties file

The config file is also well configured through my Docker Compose and the bot has Admin rights on the group.

Thank's for your help !

**Comment by shayaantx** [comment]
@Sephiphi lemme see if I can reproduce

**Comment by Sephiphi** [comment]
Thank's !

**Comment by shayaantx** [comment]
@Sephiphi 

I'm not reproducing the issue with groups, how did you configure the telegram groups property

```
telegram-token=<omitted>
telegram-private-groups=<group-name>:<group-id>
#telegram-private-channels=<channel-name>:<channel-id>
```

See above example for how to configure groups or private channels (if you're using docker this would correspond to TELEGRAM_PRIVATE_CHANNELS or TELEGRAM_PRIVATE_GROUPS)

Please post your config example omitting secrets

**Comment by Sephiphi** [comment]
@shayaantx 

Sorry for the late.

Here are my parameters in Docker Compose :

environment:
      TELEGRAM_TOKEN: <SOME_NUMBERS>:<LETTERS_AND_NUMBERS>
      TELEGRAM_PRIVATE_GROUPS: Plex:<NUMBERS_WITHOUT_-100>
      LIDARR_URL: http://1.2.3.4:8686
      LIDARR_TOKEN: <MY_TOKEN>
      LIDARR_DEFAULT_QUALITY_PROFILE: Lossless
      LIDARR_DEFAULT_METADATA_PROFILE: Standard
      LIDARR_PATH: /music/
      TZ: Europe/Paris

**Comment by shayaantx** [comment]
@Sephiphi sorry for late reply

So you posted

```
TELEGRAM_PRIVATE_GROUPS: Plex:<NUMBERS_WITHOUT_-100>
```

Earlier you posted

```
2023-Oct-02 21:52:20 PM [pool-5-thread-2] WARN TelegramLog - Channel BlahBlah not allowed, check properties file
```

This implies you are trying to send a message to channel "BlahBlah" but you only have configured "Plex" group.

Do you have a telegram or discord username? I can add you and we can troubleshoot more

**Comment by Sephiphi** [comment]
@shayaantx 

Sorry, I was just trying to anonymise the name of the group.

Actually, the group name is : Notifs Plex

Yeah, with the space between the two words and all.
I don't know if it can be an issue.

BUT ! I tried to do it again with the right parameters aaaand.... It seems to work. I'm completely lost to be honest.

Thank you for your help !

**Comment by shayaantx** [comment]
@Sephiphi I'll try it with spaces later tonight, spaces might cause an issue

**Comment by shayaantx** [comment]
@Sephiphi sorry for late response, I tried a telegram with spaces in it, and it worked fine (surprisingly). Would of expected it to only work with double quotes or something around it.

If you can reproduce reopen the ticket and post your discord or telegram and we can debug it live
