### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: Password login not supported on homeserver

### ISSUE THREAD

**Issue by y0da822** [shayaantx/botdarr#119]
Hi - this project looks great.  Been prepping to use it as I switch to Matrix (saved me the stress of making my own!)

I am getting this message from my matrix server- I login with just a username and password -what am I missing?

Exception in thread "main" java.lang.RuntimeException: Password login not supported on homeserver

**Comment by shayaantx** [comment]
hmmm

thats driven by this https://github.com/shayaantx/botdarr/blob/0ea239a146be667c962c5d5120634a13dcc592cf/src/main/java/com/botdarr/clients/matrix/MatrixChatClient.java#L256

it seems like if you goto https://<homeserver-url>/login a json is returned with a flow called "m.login.password"

I can add more logging here to see whats being returned in your case? @y0da822

**Comment by y0da822** [comment]
Thanks - anything I can do before making you do more work? Maybe something on my server side?

FYI - running in docker

**Comment by shayaantx** [comment]
its not more work or anything, I'll get you a curl to run to test this, probably won't be till sunday morning or sunday night tho

**Comment by y0da822** [comment]
Ok - no rush at all - this isnt critical its just a hobby - whenever.

**Comment by shayaantx** [comment]
@y0da822 sorry for late response

```
$ curl https://<home-server-url>/_matrix/client/r0/login
{"flows":[{"type":"m.login.password"},{"type":"m.login.application_service"}]}[
```

is basically what https://github.com/shayaantx/botdarr/blob/0ea239a146be667c962c5d5120634a13dcc592cf/src/main/java/com/botdarr/clients/matrix/MatrixChatClient.java#L256 is doing

what do you have set in MATRIX_HOME_SERVER_URL (if you're using docker)? Also if you run same curl (replacing home server hostname) what do you get back?

**Comment by y0da822** [comment]
Thank you - not a problem at all. I am using this ansible project to create the server.  https://github.com/spantaleev/matrix-docker-ansible-deploy/

When I curl my matrix.domain.com I get {"flows":[{"type":"m.login.password"},{"type":"m.login.application_service"}]}.

In the docker-compose file, I have matrix.domain.com as the MATRIX_HOME_SERVER

**Comment by shayaantx** [comment]
> Thank you - not a problem at all. I am using this ansible project to create the server. https://github.com/spantaleev/matrix-docker-ansible-deploy/
> 
> When I curl my matrix.domain.com I get {"flows":[{"type":"m.login.password"},{"type":"m.login.application_service"}]}.
> 
> In the docker-compose file, I have matrix.domain.com as the MATRIX_HOME_SERVER

Is it a url or hostname as the value of MATRIX_HOME_SERVER?

**Comment by y0da822** [comment]
hostname - should it be url?

**Comment by shayaantx** [comment]
> hostname - should it be url?

lemme check

**Comment by y0da822** [comment]
no rush - thank you

**Comment by shayaantx** [comment]
@y0da822 looks like it should be url, try changing it and see if it works

(cause I changed mine to hostname and it fails same way)

If it works after using url, I'll make a small change to prevent using hostnames so its more obvious

**Comment by y0da822** [comment]
That worked - I really need to learn how to read better.

**Comment by y0da822** [comment]
Thank you - have to make sure you use the URL - I didnt read thanks!!!
