### ISSUE TITLE
Matrix bot - error 302

### ISSUE THREAD

**Issue by y0da822** [shayaantx/botdarr#121]
Thanks for all - got it to connect etc but now as soon as it connects (rate limiting disabled), I get a 302 error but it doesnt indicate why in any of the logs.

status-code=302, reason=Found

When trying to add

**Comment by shayaantx** [comment]
@y0da822 want to troubleshoot live some time this week?

**Comment by shayaantx** [comment]
@y0da822 can you post zip of full logs

**Comment by y0da822** [comment]
Sorry - was busy past couple of days.  What zip would you want?  

Any idea what you think the 302 is?

**Comment by shayaantx** [comment]
@y0da822 a zip of the entire logs folder and can you post full log entry that shows the 302?

**Comment by y0da822** [comment]
What log file would that be in? @shayaantx

**Comment by shayaantx** [comment]
@y0da822 usually if you're using docker there is a logs folder mount, I'd want to see all the logs here

![image](https://github.com/shayaantx/botdarr/assets/5449086/88a3dc95-8878-4d22-aedd-bb48cc62ca65)

**Comment by shayaantx** [comment]
@y0da822 if you want to add me on matrix, we can troubleshoot directly shayaantx@shayaantx:matrix.org

**Comment by y0da822** [comment]
Cool. Will be back on tomorrow. Busy with work lately. Thank you.

**Comment by y0da822** [comment]
You have discord,? I can add you on there.

**Comment by shayaantx** [comment]
> You have discord,? I can add you on there.

rude_yoshi

**Comment by shayaantx** [comment]
> You have discord,? I can add you on there.

did you ever add me? didn't see a request? maybe post your discord and ill add you

**Comment by y0da822** [comment]
I tried to add you - it didnt let me.  Mine is the same as my username

**Comment by y0da822** [comment]
all works now - was the url path had to add RADARR_URL_BASE and SONARR_URL_BASE to docker compose - thank you!
