### ISSUE TITLE
Error! Could not add artist, status-code=400, reason=Bad Request (Lidarr/Discord)

### ISSUE THREAD

**Issue by idio-sync** [shayaantx/botdarr#125]
A few days ago, I started getting errors adding artists in lidarr via the botdarr discord bot. It had previously been working fine for months and I don't believe anything changed, I'm not sure what's up. After investigating, it looks like the lidarr api call is formatted wrong but I have no info aside from that. Running lidarr and botdarr via docker in UnRaid. Any help would be appreciated!

Discord error:
![Screenshot 2024-09-01 190034](https://github.com/user-attachments/assets/ea82e888-399d-4d38-ad08-ba67f042b512)

Error msg in lidarr:

Lidarr.Api.V1.Artist.ArtistController.AddArtist (Lidarr.Api.V1)

```
{
  "$.statistics.albumCount": {
    "errors": [
      {
        "errorMessage": "The JSON value could not be converted to System.Int32. Path: $.statistics.albumCount | LineNumber: 0 | BytePositionInLine: 3276."
      }
    ],
    "validationState": "invalid",
    "isContainerNode": false
  }
}
```

**Comment by shayaantx** [comment]
ill take a look 2moro and see if i can reproduce, what version of lidarr?

**Comment by idio-sync** [comment]
> ill take a look 2moro and see if i can reproduce, what version of lidarr?

Rad, thank you!

![Screenshot 2024-09-01 212632](https://github.com/user-attachments/assets/d7856f35-ec5d-413a-9133-b140971ce6c9)

**Comment by shayaantx** [comment]
So I tried with lidarr 1.4.5.3639 and it does work, will try with lidarr 2.5.1, but I never added support for lidarr 2.x so probably why its not working

![image](https://github.com/user-attachments/assets/bebd10e9-2908-4cd0-a659-ff32c34a3d4e)

I'll look into this and see what it will take

**Comment by shayaantx** [comment]
did you by chance upgrade your lidarr recently?

**Comment by idio-sync** [comment]
Ah, makes sense. Looks like the docker base was bumped from 2.5.1.4312 to 2.5.2.4317 two weeks ago, but it worked a good week and a half after that.

**Comment by idio-sync** [comment]
Ah, that makes sense. Looks like the docker image was updated 16 days ago, but it worked a good week or so after that.  

I'm running the lidarr-on-steroids image if that makes any difference (https://github.com/youegraillot/lidarr-on-steroids). It's the plugin branch alongside some other things.

**Comment by shayaantx** [comment]
@idio-sync I published a version of botdarr where i fixed some things, https://hub.docker.com/layers/shayaantx/botdarr/99.99.15/images/sha256-92a8c103de15852d7044ccd3a6bd7d87e1df2caae3a8046d3604d0a25448e8c6?context=repo

can you try it and let me know if you find any issues?

I fixed the add artist and lookup artist and could add artist you mentioned earlier

**Comment by idio-sync** [comment]
That worked!

![image](https://github.com/user-attachments/assets/da8dbed7-a564-4194-a2bd-8361e800a062)

This is something separate, but I figure while I have you, is there any way to change the success message?

**Comment by shayaantx** [comment]
> That worked!
>
> This is something separate, but I figure while I have you, is there any way to change the success message?

I'm open to changing anything if it makes sense, what do you have in mind?

**Comment by idio-sync** [comment]
Just generally cleaning it up, removing the detail=created and making it sound more natural. "(Artist X) was added successfully!" or something. Not a big deal if you don't feel like doing it, just curious. Thank you for your work btw.

**Comment by shayaantx** [comment]
@idio-sync yea i can change all the messages to be more natural

can you confirm the rest of the commands work with that custom version i built + these changes, cause I didn't test everything fully? (like are notifications showing etc etc)

**Comment by idio-sync** [comment]
Notifications seem to be working, though I tried to add another artist and the bot reported that they were already present, while still adding the entry to lidarr. I verified that the artist was not present previously, and the "added" in lidarr matched up to when I sent the command, so it was the bot that added the entry.

![image](https://github.com/user-attachments/assets/35d3d84b-7d7d-4f9e-84c1-ecf9a2d3d216)

I've added several artists after, and they have all worked fine. I'm not sure if that was a one-off or if there's any way to reproduce it.

**Comment by shayaantx** [comment]
@idio-sync thats weird, the bot does keep a local cache for quicker calls, but weird things happen usually if you delete something in lidarr after adding via botdarr (since cache won't get updated immediately)

if it keeps happening lemme know

**Comment by shayaantx** [comment]
@idio-sync sorry i was sick and forgot about this, ill clean up the PR, and merge this weekend

**Comment by shayaantx** [comment]
@idio-sync check out https://github.com/shayaantx/botdarr/releases/tag/5.6.15, has the lidarr fixes + updates to "add" messaging for radarr, sonarr, lidarr
