### ISSUE TITLE
add https for matrix chat client api calls

### ISSUE THREAD

**Issue by shayaantx** [shayaantx/botdarr#20]

**Comment by jordemort** [comment]
I'd like this too, my Matrix server and my *arrs run in different locations and I don't want to punch a plaintext hole to the Matrix server for this

**Comment by shayaantx** [comment]
> I'd like this too, my Matrix server and my *arrs run in different locations and I don't want to punch a plaintext hole to the Matrix server for this

I actually see this working in my own matrix server, are you seeing something different? I just specify an https url for the matrix server url and it sends commands just fine.

Lemme know

**Comment by jordemort** [comment]
@shayaantx No, I haven't actually tried it because the docs said it wasn't supported; I'll give it a spin

**Comment by shayaantx** [comment]
@jordemort sorry about that, when I wrote it I was using http, but I think over time I changed it so it shouldn't matter if its http or https anymore.

let me know if you have any issues

**Comment by shayaantx** [comment]
@jordemort assuming this worked? or you disappeared into the ether? or switched to another bot?

lemme know if you encounter any other issues

**Comment by jordemort** [comment]
Haven't had time to try yet, maybe this weekend. I'll let you know if I run into any trouble, otherwise you can assume it works :)
