### ISSUE TITLE
Full support for environment variable driven configuration

### ISSUE THREAD

**Issue by onedr0p** [shayaantx/botdarr#22]
It would be nice if you could add support for configuring the app via environment variables, not only the `config.properties`. This would make the configuration much easier when using Docker.

Thanks!

**Comment by shayaantx** [comment]
@onedr0p sure, I'll try to put up a PR for this, this weekend

**Comment by shayaantx** [comment]
https://github.com/shayaantx/botdarr/pull/23

if there is anything else you were thinking with this request let me know, otherwise ill merge tomorrow (or tonight)

**Comment by shayaantx** [comment]
merged this, lemme know of any issues or other suggestions, thanks
