### ISSUE TITLE
Docker images for armhf (raspberry pi)

### ISSUE THREAD

**Issue by marnunez** [shayaantx/botdarr#39]
Hi! I haven't got much experience with Java, but could botdarr be ported to arm?

**Comment by shayaantx** [comment]
yea sure, lemme look into it

**Comment by shayaantx** [comment]
so I looked into creating this arm image, see below (there would be a latest for arm32v7 plus release image for arm and other latest would be the normal for 64 bit arch's including 64 bit arm)

I didn't see a way to merge 32bit and 64 bit images in a single tag using github workflows, so I kept them separate. I did have to use a 32bit arm image of openjdk8 to support this, which shouldn't affect the bot. I have an old raspberry pi I can test this on tomorrow.

Let me know if there was anything else you wanted here (see example below)

![image](https://user-images.githubusercontent.com/5449086/117558711-a0b32f00-b04d-11eb-83ff-c430297d4257.png)

**Comment by shayaantx** [comment]
@marnunez sorry this is so late, but now you can reference docker images for arm64 or armv7 (I tested armv7 on my rpi and it does work)

There are few new images:
latest-arm32v7
<version>-arm32v7
latest
<version>

Anything with the suffix of arm32v7 will work on a 32bit arm (didn't test on anything lower than v7)
The existing tags (latest, 5.1.9, etc) now have support for arm64 as well as existing amd64

I spent most of the time trying to troubleshoot the underlying openjdk armv7 images out there and the one from https://github.com/AdoptOpenJDK/openjdk-docker/blob/c945a5b588b63553a7bb36c28b6751716e35070c/8 didn't work for me out of the box on my rpi. Was always getting below error

```
root@88de1778d3a2:/home/botdarr# java -version
java: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
```

So I copied their file and modified it to install libatomic (to fix above error) and made some other modifications that were specific to buildx weirdness.

Buildx was a whole other story, basically there is no functionality currently to associate a platform in buildx with a specific dockerfile. So I ended up having to run 2 buildx build/push steps for 64 bit vs 32 bit.

It got worse when for some reason armv7 builds were throwing missing file errors (seen here https://github.com/docker/buildx/issues/495). I ended up making a custom build builder before trying to build the v7 image, which seemed to work.

Only unfortunate thing out of this is mixing the images with same tag wasn't trivial (at least now it isn't cause I don't have time atm to investigate how to merge them into same docker manifest)

Please let me know if you find any issues or have any further suggestions.
