### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by JohnnyB813** [shayaantx/botdarr#5]
1. Reaction based interaction with the bot. (i.e. the bot responds to a movie request with a 👍 and 👎 and asks the user to chose one)

2. add a prefix to the bot to distinguish commands from normal text. (i.e. ! or @ or $. and have it configurable via the properties file or using the command !prefix in discord)

3. Limit movie search results to the top 5 from radarr, and possible have a reaction based 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣  to select which of the top 5 you would like to download.

**Comment by shayaantx** [comment]
In https://github.com/shayaantx/botdarr/releases/tag/4.4.13 I added discord thumbs up reaction if you want to check it out. I'm not sure what you want thumbs down to, but linking thumbs up to adding content makes sense to me.

I think adding a configurable limit on search results also makes sense and I'll add that at some point this week, same with the configurable prefix.

However I'm not sure I understand the usefulness of number reactions. Are you asking for the ability to return X number of results that have already been ranked? Or are you asking to be able to rank results and then in future searches return only ranked items greater than 5? (feel free to PM me on discord and we can talk more about it)

**Comment by shayaantx** [comment]
In https://github.com/shayaantx/botdarr/releases/tag/4.4.25 I added ability to configure max number of downloads to show and max number of results to show, fyi

**Comment by shayaantx** [comment]
In https://github.com/shayaantx/botdarr/releases/tag/4.4.26 I added the ability to configure a prefix for all commands via property "command-prefix". The default prefix is now /
