### ISSUE TITLE
Allow Notification Editing

### ISSUE THREAD

**Issue by marjoemitchell** [shayaantx/botdarr#51]
Currently botdarr notifies slack channel with a lot of other info like errors and downloads etc. It would be nice to have the option to decide exactly what alerts it can ignore.

**Comment by shayaantx** [comment]
right, lemme setup my slack workspace again, and see what alerts we can add some configuration around 

were there particular type of notifications you wanted to ignore?

**Comment by shayaantx** [comment]
So if you set MAX_DOWNLOADS_TO_SHOW=0 in your setup downloads will stop showing up, however I'm not clear what errors you are referring to?
Are you talking about radarr/sonarr specific errors in the download messages or the entire download message?

**Comment by marjoemitchell** [comment]
Thanks for the quick response and for botdarr! Ill give that a go for downloads. One of the error messages I see in slack is when my unraid server shuts down botdarr sends a notification for connections refused:

`Error - Requested failed with exception, e=Connect to 192.168.1.5:7878 [/192.168.1.5] failed: Connection refused (Connection refused),class=class org.apache.http.conn.HttpHostConnectException`

**Comment by shayaantx** [comment]
Yea I can see how that would be annoying when botdarr is up but radarr/sonarr is down. I'll put up a PR tonight or tomorrow that only logs the failure to connect instead of sending notifications for it.

**Comment by shayaantx** [comment]
added https://github.com/shayaantx/botdarr/pull/52, just need to add a test or two, then I'll merge

**Comment by shayaantx** [comment]
@marjoemitchell I modified download notifications to not send notifications but log silently if the endpoints are down. Please let me know of any other issues or improvements that I can make that will help you.

Thanks

**Comment by marjoemitchell** [comment]
@shayaantx thanks! I was actually using ombibot before and there are some nice features added in for messages, where the response for your search includes downloads buttons. I pulled down the code for botdarr to see if I could get it going, but it's definitely too much for my current skills.

**Comment by shayaantx** [comment]
@marjoemitchell that seems possible, go ahead put an enhancement with details, and I'll take a look.

I did add the ability to react with thumbs up to search results in discord which adds, but we could add that for slack too. Plus some download buttons as well.

**Comment by shayaantx** [comment]
> @shayaantx thanks! I was actually using ombibot before and there are some nice features added in for messages, where the response for your search includes downloads buttons. I pulled down the code for botdarr to see if I could get it going, but it's definitely too much for my current skills.

the code is actually pretty easy to change (or I hope it is), if you're on discord or something, send me your handle, and we can discuss more. I'm always down to help someone who wants to make changes

**Comment by marjoemitchell** [comment]
@shayaantx I'm super late to the game but getting into some coding through work. I wouldn't mind giving it a go if you didn't mind setting me in the right direction, that's really nice of you to offer that. Discord is thegorgotron#8177

**Comment by marjoemitchell** [comment]
@shayaantx so I set the download notification setting to 0, and recently updated to the latest. Slack later got flooded with "failed to import" notifications from botdarr.

**Comment by shayaantx** [comment]
hmm I added you on discord lets troubleshoot live today or 2moro

**Comment by marjoemitchell** [comment]
@shayaantx ok I think I know what the issue was. I was unable to find the config file in my unraid server (Im running this in docker) so I execd in and changed the properties file, forgetting that on an update those would get changed back to default. Im used to the containers having a specified installed location as a variable during setup (for me config /mnt/cache/appdata). I went back in and read the readme and realized I missed the section on Misc Variables. I can easily set the values to show there and it should hold for future updates. Sorry for the confusion, this can be closed.
