### ISSUE TITLE
Discord - Need to support slash commands

### ISSUE THREAD

**Issue by shayaantx** [shayaantx/botdarr#54]
I think in next couple of months we won't be able to read text freely from events, so I'll have to workaround it.

Seems like the underlying discord library I use might have solved this already somewhat, https://github.com/DV8FromTheWorld/JDA/pull/1501

**Comment by nmcc1212** [comment]
+1 for slash commands

**Comment by shayaantx** [comment]
I'm trying to get through another issue and its just going slowly cause of life/work/etc. I'm hoping to finish this other issue, then I can tackle some of these chat client specific issues

**Comment by shayaantx** [comment]
@nmcc1212 always open to PR's and what not :)

**Comment by shayaantx** [comment]
@nmcc1212 fyi I pushed an experimental tag for this functionality in dockerhub called 5.4.0-experimental if you wanna test it out. You'll need to re-invite your bot with new permission

see https://github.com/shayaantx/botdarr/tree/feature/discord-slash-commands#discord-bot-installation for some details on enabling slash command support.

I still need to write some test cases, then I'll merge it.

**Comment by Aerya** [comment]
Hi,

I'm trying your Bot, using the "experimental" Docker but got an error related to the /

```
2022-May-21 08:19:57 AM [main] ERROR com.botdarr.Config - Error loading properties file
java.lang.RuntimeException: Cannot use / command prefix in discord since / command is used by discord slash commands
	at com.botdarr.clients.discord.DiscordBootstrap.validatePrefix(DiscordBootstrap.java:165) ~[botdarr-release.jar:?]
	at com.botdarr.Config.<init>(Config.java:103) [botdarr-release.jar:?]
	at com.botdarr.Config.getConfig(Config.java:32) [botdarr-release.jar:?]
	at com.botdarr.Config.getChatClientBootstrap(Config.java:128) [botdarr-release.jar:?]
	at com.botdarr.BotdarrApplication.main(BotdarrApplication.java:12) [botdarr-release.jar:?]
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Cannot use / command prefix in discord since / command is used by discord slash commands
	at com.botdarr.Config.<init>(Config.java:107)
	at com.botdarr.Config.getConfig(Config.java:32)
	at com.botdarr.Config.getChatClientBootstrap(Config.java:128)
	at com.botdarr.BotdarrApplication.main(BotdarrApplication.java:12)
Caused by: java.lang.RuntimeException: Cannot use / command prefix in discord since / command is used by discord slash commands
	at com.botdarr.clients.discord.DiscordBootstrap.validatePrefix(DiscordBootstrap.java:165)
```

Here's my Docker, what's wrong with it?
```
docker run -d \
--name botdarr \
--restart=always \
-e DISCORD_TOKEN="abc123" \
-e DISCORD_CHANNELS="#reqz" \
-e RADARR_URL="https://radarr.upandclear.org" \
-e RADARR_TOKEN="def456" \
-e RADARR_DEFAULT_PROFILE="HD-1080p" \
-e RADARR_PATH="/movies/unionfsRCLONECACHE/Films" \
-e SONARR_URL="https://sonarr.upandclear.org/" \
-e SONARR_TOKEN="ghi789" \
-e SONARR_DEFAULT_PROFILE="HD" \
-e SONARR_PATH="/tv/unionfsRCLONECACHE/Series" \
-e MAX_DOWNLOADS_TO_SHOW="20" \
-e MAX_RESULTS_TO_SHOW="20" \
-e COMMAND_PREFIX="/" \
-v /volume1/docker/botdarr/db:/home/botdarr/database \
-v /volume1/docker/botdarr/logs:/home/botdarr/logs \
--label=com.centurylinklabs.watchtower.enable=true \
shayaantx/botdarr:5.4.0-experimental
```

Thanks

**Comment by shayaantx** [comment]
@Aerya if you use discord by default, slash commands are enabled, but you can't use "/" as a prefix (since there are basically two modes - with and without slash commands), so you can unset that environment variable, and you should have slash commands automatically + the non slash command mode (so you will / and ! prefixes available).

Although I wonder if you will have issues with https://github.com/shayaantx/botdarr/issues/31, if you do let me know

**Comment by Aerya** [comment]
Thanks.

I miss something as the bot doesn't work at all (with -e COMMAND_PREFIX="!" \)
![ ](https://i.imgur.com/fTuki9d.png)

No matter, I already use Requestrr and also tested Doplarr that works out of the box.

I might give a new try to your bot the day i'll use Telegram more than Discord. Thank you for your work.

**Comment by shayaantx** [comment]
@Aerya can you post a zip of the logs 

you can add me on discord and I can take a deeper look, Rude Yoshi#0570

does your channel name actually contain "#"
```
-e DISCORD_CHANNELS="#reqz" \
```

**Comment by Aerya** [comment]
OMG! Call me noob :'(

I had to remove the # in the channel name. It obviously works like a charm :)
![](https://i.imgur.com/VjQhi44.png)

I can now write my tutorial about your work. Thanks!

**Comment by shayaantx** [comment]
@Aerya you're not a n00b. I think I can probably do some pre processing on channel names entered to remove any special characters to avoid this, thanks for finding this edge case
