### ISSUE TITLE
Overwrite old news

### ISSUE THREAD

**Issue by ExtraMediumPizza** [shayaantx/botdarr#6]
Time sensitive programs should be overwritten to save storage space. Every 3 - 8 days depending on storage needs.

**Comment by shayaantx** [comment]
I think this makes sense, but sonarr (the tool the bot interacts with shows) does not have an api option that I see to delete seasons or episodes individually. It only lets me delete the an entire series

I'd also prefer to not introduce features that automatically delete content tbh.
