### ISSUE TITLE
Constant notifications - No downloads

### ISSUE THREAD

**Issue by elessyl** [shayaantx/botdarr#66]
I observed a rather annoying behaviour of the bot:
- in every 5 minutes it is spamming every configured backend status about:
   - "No movies downloading"
   - "No shows downloading"
   - "No artists downloading"

Are there any way to disable this ? It is totally pointless and just generating unnecessary traffic...

Bot version: 5.3.1
Configured backends: radarr, lidarr, sonarr
Media channels: discord and telegram

There are no errors in the logs.

**Comment by shayaantx** [comment]
I agree this is pretty annoying, I'm completely reworking notifications in https://github.com/shayaantx/botdarr/issues/34 but until thats done I put up https://github.com/shayaantx/botdarr/pull/67 which gets rid of this periodic notification (it will still show if you use the actual downloads command manually)

later today or tomorrow morning I'll fix test cases and merge it.

**Comment by shayaantx** [comment]
@elessyl I merged, new version should be built momentarily, let me know if you have any other issues
