### ISSUE TITLE
Discord integration not working

### ISSUE THREAD

**Issue by EricCartman912** [shayaantx/botdarr#68]
I tried setting up botdarr with discord. The docs were quite helpful and I got the docker container and the discord bot working together perfectly.

However, the bot does not respond to or detect any commands whatsoever, including the help command, with an exclamation at the beginning of it.

**Comment by shayaantx** [comment]
hi, any errors in the logs?

if you wanna add me on discord I can take a look

**Comment by Suyash9** [comment]
Hello,

There are absolutely no errors in the logs or in the docker logs either which was the surprising part of it

**Comment by EricCartman912** [comment]
Hello,

There are absolutely no errors in the logs. In the discord logs it shows connection was successful. The radarr logs are completely empty. 

The only thing I saw was warnings for sonarr and lidarr which I have not setup.

**Comment by shayaantx** [comment]
add me on discord and I'll take a look, @EricCartman912 

Rude Yoshi#0570

**Comment by EricCartman912** [comment]
Discord says that I’m unable to send you friend requests as this user is not accepting friend requests

**Comment by shayaantx** [comment]
try again @EricCartman912

**Comment by shayaantx** [comment]
we ended up figuring this out, just a mis config in discord settings using channel ids instead of channel names.

I updated readme + added some more logs to make it obvious the channel config was the issue + made the ability to turn on debug logging via an environment variable

let me know if you have any other issues
