### ISSUE TITLE
Error message when typing command

### ISSUE THREAD

**Issue by JulienSambre** [shayaantx/botdarr#78]
Hi!

Since the update to the 5.4.0, when I type a command ("!status" for example), I see just below the result a lot of time the same error message (>10) : 

![image](https://user-images.githubusercontent.com/14327288/171346038-d8b6c8c5-bf10-4bd9-a6c2-c387fa61f44a.png)

If I rollback to the previsous version (5.3.5, no issue) : 

![image](https://user-images.githubusercontent.com/14327288/171346159-deac8475-1004-4d8f-a5cd-a2b7079e1ebe.png)

**Comment by shayaantx** [comment]
@JulienSambre that doesn't sound good, what chat client are you using?

can you post a zip of the logs directory too?

I'll take a look after work today

**Comment by shayaantx** [comment]
looks like you're using matrix/element, cause I reproduced it there, will fix shortly

**Comment by shayaantx** [comment]
5.4.1 should have the fix (building now), please let me know if you have any other issues @JulienSambre
