### ISSUE TITLE
getting error 400 when attempting to add movie/tv show (telegram/discord)

### ISSUE THREAD

**Issue by IvayloMilenkov** [shayaantx/botdarr#81]
running in docker instance
as stated in title, bot is connected, status shows green dot in both radarr and sonarr, tried it both on discord and telegram, whenever i click on "add" it just spits out Error! - Could not add movie, status-code=400, reason=Bad Request

**Comment by shayaantx** [comment]
hi @IvayloMilenkov can you post your logs folder as a zip, or if you want to troubleshoot live post your telegram/discord, and I'll add you and we continue

also what version of radarr?

also what full command are you using?

**Comment by IvayloMilenkov** [comment]
Hello there, just found the issue, was to do with the path i set for radarr and sonarr, closing the issue (needed to set the path as seen in radarr/sonarr media management)

**Comment by shayaantx** [comment]
@IvayloMilenkov cool, lemme know if you have anymore issues
