### ISSUE TITLE
Add support for sonarr v4

### ISSUE THREAD

**Issue by JulienSambre** [shayaantx/botdarr#83]
Hi!

First of all, thanks for the bot, I use it extensively with my AI to notify me when movies & co are downloading and it works like a charm.

I'd like to know if there is a plan to support Sonarr v4 API : I updated to Sonarr v4 a few weeks ago and it broke botdarr. I think there are changes on the Sonarr v4 API.

Thanks!

**Comment by shayaantx** [comment]
@JulienSambre I'll try to take a look at this weekend or sometime during this week, didn't know they had a new version of sonarr out. I'm also open to PR's too

**Comment by JulienSambre** [comment]
Thanks!

**Comment by shayaantx** [comment]
@JulienSambre so I been making some changes to this, not sure what version you were on prior to sonarr v4, but it looks like at least on sonarr 3.0.7.1477 at least one of the api calls is broken (one that shows downloads).
I'm going thru them all again on v3 and v4 to see what is working and what isn't.

**Comment by shayaantx** [comment]
@JulienSambre I added this support in 5.6.0, but you need to turn on a special property to make it work (SONARR_V4=true in docker or sonarr-v4=true in properties in a manual installation - see readme)

lemme know if you have issues, cause I had to refactor a decent bit to make it easier to change/support different api versions in future (so I may have broken some stuff :) ).

**Comment by shayaantx** [comment]
when sonarr v3 is EOL-ed I'll remove this property fyi
