### ISSUE TITLE
Discord: Requested failed with exception, e=Not a JSON Object: [],class=class java.lang.IllegalStateException

### ISSUE THREAD

**Issue by grodz21** [shayaantx/botdarr#88]
Getting on discord "Requested failed with exception, e=Not a JSON Object: [],class=class java.lang.IllegalStateException"

I'm running the docker image in unRaid.

When I open the logs all I see is this:

INFO: Finished Loading!
2022-Dec-25 21:50:11 PM [main] WARN  com.botdarr.Config - Lidarr commands are not enabled, make sure you set the lidarr url, path, token, default profile
2022-Dec-25 21:50:12 PM [JDA MainWS-ReadThread] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
2022-Dec-25 21:50:12 PM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
2022-Dec-25 21:52:12 PM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2
2022-Dec-25 21:54:12 PM [pool-2-thread-1] WARN  com.botdarr.api.CacheProfileStrategy - Did not find any profiles available for caching, class=class com.botdarr.api.sonarr.SonarrApi$2

If it matters, I'm trying to setup the bot on discord to get it to use sonarr and radarr.

Thank you

**Comment by shayaantx** [comment]
@grodz21 which docker image?

can you post your docker setup excluding sensitive values?

can you zip logs and post em?

Send me your discord and I'll add you and we can troubleshoot live

**Comment by grodz21** [comment]
![Screenshot 2022-12-26 at 08-11-58 Tower_UpdateContainer](https://user-images.githubusercontent.com/6210593/209567134-2b424790-45fc-4914-a563-5b84da318bbe.png)

This are the only logs where there is something in them.
[botdarr_logs.zip](https://github.com/shayaantx/botdarr/files/10304119/botdarr_logs.zip)

The docker image is= botdarr by  joroga22's Repository
HomeAutomation

Discord=   [DLC]Seeker#7805

**Comment by shayaantx** [comment]
@grodz21 sent you a friend request

what version of sonarr and radarr are you running?

**Comment by grodz21** [comment]
> @grodz21 sent you a friend request
> 
> what version of sonarr and radarr are you running?


Radarr version 4.2.4.6635
Sonarr version 3.0.9.1549

**Comment by shayaantx** [comment]
this was a bug from 5.6.0, fixed in 5.6.1
